INSERT INTO Restaurants (Name, Address, PhoneNumber) VALUES 
('Mi Casa Chicago North', '1234 W Irving Park Rd, Chicago, IL 60613', '773-555-1010'),
('Mi Casa Greektown', '456 S Halsted St, Chicago, IL 60607', '312-555-2020'),
('Mi Casa River North', '789 N Clark St, Chicago, IL 60654', '312-555-3030'),
('Mi Casa Skokie', '1025 E Dempster St, Skokie, IL 60077', '847-555-4040'),
('Mi Casa Elmhurst', '250 W North Ave, Elmhurst, IL 60126', '630-555-5050'),
('Mi Casa Oak Park', '317 W Lake St, Oak Park, IL 60301', '708-555-6060'),
('Mi Casa Downers Grove', '842 Main St, Downers Grove, IL 60515', '630-555-7070'),
('Mi Casa Lombard', '210 S Main St, Lombard, IL 60148', '630-555-8080'),
('Mi Casa Glen Ellyn', '678 Roosevelt Rd, Glen Ellyn, IL 60137', '630-555-9090'),
('Mi Casa Wicker Park', '1550 N Milwaukee Ave, Chicago, IL 60647', '773-555-1111'),
('Mi Casa Downtown', '432 W Randolph St, Chicago, IL 60606', '312-555-1212'),
('Mi Casa Naperville', '920 Ogden Ave, Naperville, IL 60563', '630-555-1313');

INSERT INTO MenuItems (RestaurantID, Name, Description, Price, Category, IsAvailable) VALUES
(1, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(1, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(1, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(1, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(1, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(1, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(1, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(1, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(1, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(1, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(1, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(1, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(1, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(1, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(1, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(1, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(1, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(1, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(1, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(1, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(1, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(1, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(1, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(1, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(2, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(2, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(2, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(2, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(2, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(2, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(2, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(2, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(2, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(2, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(2, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(2, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(2, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(2, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(2, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(2, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(2, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(2, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(2, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(2, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(2, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(2, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(2, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(2, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(3, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(3, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(3, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(3, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(3, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(3, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(3, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(3, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(3, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(3, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(3, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(3, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(3, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(3, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(3, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(3, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(3, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(3, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(3, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(3, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(3, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(3, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(3, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(3, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(4, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(4, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(4, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(4, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(4, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(4, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(4, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(4, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(4, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(4, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(4, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(4, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(4, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(4, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(4, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(4, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(4, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(4, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(4, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(4, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(4, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(4, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(4, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(4, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(5, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(5, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(5, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(5, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(5, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(5, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(5, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(5, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(5, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(5, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(5, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(5, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(5, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(5, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(5, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(5, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(5, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(5, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(5, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(5, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(5, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(5, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(5, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(5, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(6, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(6, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(6, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(6, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(6, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(6, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(6, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(6, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(6, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(6, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(6, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(6, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(6, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(6, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(6, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(6, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(6, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(6, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(6, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(6, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(6, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(6, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(6, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(6, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(7, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(7, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(7, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(7, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(7, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(7, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(7, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(7, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(7, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(7, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(7, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(7, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(7, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(7, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(7, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(7, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(7, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(7, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(7, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(7, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(7, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(7, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(7, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(7, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(8, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(8, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(8, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(8, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(8, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(8, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(8, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(8, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(8, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(8, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(8, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(8, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(8, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(8, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(8, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(8, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(8, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(8, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(8, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(8, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(8, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(8, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(8, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(8, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),


(9, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(9, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(9, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(9, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(9, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(9, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(9, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(9, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(9, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(9, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(9, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(9, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(9, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(9, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(9, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(9, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(9, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(9, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(9, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(9, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(9, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(9, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(9, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(9, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(10, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(10, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(10, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(10, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(10, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(10, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(10, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(10, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(10, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(10, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(10, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(10, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(10, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(10, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(10, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(10, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(10, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(10, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(10, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(10, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(10, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(10, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(10, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(10, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(11, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(11, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(11, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(11, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(11, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(11, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(11, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(11, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(11, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(11, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(11, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(11, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(11, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(11, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(11, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(11, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(11, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(11, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(11, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(11, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(11, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(11, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(11, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(11, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE),

(12, 'Carne Asada Tacos', 'Three tacos with grilled steak, cilantro, and onions on corn tortillas. Served with rice and beans.', 14.99, 'Tacos', TRUE),
(12, 'Al Pastor Tacos', 'Marinated pork with pineapple, cilantro, and onions on soft corn tortillas.', 13.99, 'Tacos', TRUE),
(12, 'Carnitas Tacos', 'Slow-cooked pork topped with onions and cilantro, served with tomatillo salsa.', 13.49, 'Tacos', TRUE),
(12, 'Pollo Asado Tacos', 'Grilled chicken tacos with lettuce, pico de gallo, and chipotle crema.', 12.99, 'Tacos', TRUE),
(12, 'Barbacoa Tacos', 'Tender shredded beef tacos served with cilantro, onion, and lime.', 13.99, 'Tacos', TRUE),
(12, 'Fish Tacos', 'Three soft tacos filled with crispy fish, cabbage slaw, and spicy crema.', 14.49, 'Tacos', TRUE),
(12, 'Shrimp Tacos', 'Grilled shrimp with avocado, cabbage, and chipotle mayo on flour tortillas.', 15.49, 'Tacos', TRUE),
(12, 'Veggie Tacos', 'Grilled peppers, onions, zucchini, and mushrooms topped with queso fresco.', 12.49, 'Tacos', TRUE),
(12, 'Birria Tacos', 'Crispy beef tacos with melted cheese, served with consomé for dipping.', 16.49, 'Tacos', TRUE),
(12, 'Street Tacos Combo', 'Choice of three tacos: asada, pastor, or carnitas. Served with rice and beans.', 15.99, 'Tacos', TRUE),
(12, 'Classic Beef Burrito', 'Ground beef, rice, beans, cheese, and red enchilada sauce wrapped in a flour tortilla.', 12.99, 'Burritos', TRUE),
(12, 'Chicken Burrito', 'Grilled chicken, rice, black beans, pico de gallo, and sour cream in a flour tortilla.', 12.49, 'Burritos', TRUE),
(12, 'Carnitas Burrito', 'Slow-roasted pork with rice, pinto beans, cheese, and verde sauce.', 13.49, 'Burritos', TRUE),
(12, 'Carne Asada Burrito', 'Marinated steak with cilantro-lime rice, beans, cheese, and guacamole.', 14.99, 'Burritos', TRUE),
(12, 'Veggie Burrito', 'Grilled veggies, rice, beans, corn, and queso fresco in a spinach tortilla.', 11.99, 'Burritos', TRUE),
(12, 'Fajita Burrito', 'Grilled steak or chicken with peppers, onions, rice, and melted cheese.', 14.49, 'Burritos', TRUE),
(12, 'California Burrito', 'Steak, fries, cheese, pico de gallo, and sour cream wrapped in a large tortilla.', 15.99, 'Burritos', TRUE),
(12, 'Burrito Supreme', 'Beef burrito topped with enchilada sauce, melted cheese, lettuce, tomato, sour cream, and guacamole.', 16.49, 'Burritos', TRUE),
(12, 'Chorizo Burrito', 'Spicy Mexican sausage with eggs, cheese, and potatoes in a warm flour tortilla.', 13.49, 'Burritos', TRUE),
(12, 'Wet Burrito', 'Large burrito smothered in red or green sauce and melted cheese, with rice and beans.', 16.99, 'Burritos', TRUE),
(12, 'Burrito Bowl', 'Deconstructed burrito with choice of protein, rice, beans, veggies, and toppings.', 12.99, 'Bowls', TRUE),
(12, 'Breakfast Burrito', 'Scrambled eggs, bacon, potatoes, cheese, and pico de gallo wrapped in a warm tortilla.', 10.99, 'Breakfast', TRUE),
(12, 'Mini Tacos', 'Five mini tacos with your choice of meat, topped with cilantro and onions.', 11.99, 'Tacos', TRUE),
(12, 'Mi Casa Burrito Combo', 'One large burrito served with a side of rice, refried beans, and small salad.', 15.99, 'Burritos', TRUE);